name: Handle Secrets Workflow
on: [push]
env:
  REPO_SECRET: ${{ secrets.REPO_SECRET }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Access secret
        run: echo "The secret value is ${{ env.REPO_SECRET }}"